services:
  web:
    container_name: ai-interview-s
    image: ai-interview-s
    build: ./WebApp
    command: python app.py
    volumes:
      - .:/WebApp
    ports:
      - 5000:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
