services:
  workspace:
    build:
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:delegated
    command: sleep infinity
    networks:
      - ai-interview-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1

networks:
  ai-interview-network:
    driver: bridge
